# Generated by Django 4.0 on 2021-12-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_perice', models.IntegerField(default=0)),
                ('product_date', models.DateTimeField(auto_now_add=True)),
                ('product_image', models.ImageField(upload_to='product/image')),
            ],
        ),
    ]
