# Generated by Django 4.0 on 2021-12-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('phone', models.IntegerField(default=91)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.IntegerField()),
                ('re_password', models.IntegerField()),
            ],
        ),
    ]
