# Generated by Django 4.0 on 2022-01-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='customer',
            name='re_password',
            field=models.CharField(max_length=8),
        ),
    ]
